export const defaultState = {
	sessionNum: 0,
	numQuestions: 0,
	fontSize: "medium",
	questionAns: "",
	questionAnsSum: "",
	questions: "",
	questionSum: "",
	Anagram: {
		Anagram_recess: {
			title: "Saving Recess",
			numOfText: 4,
			text1: "One reason is that recess is healthy for kids.",
			text2: "Thatís why I think it is important to try to save recess.",
			text3: "Some schools are getting rid of recess, but I think recess is good for students.",
			text4: "For example, kids can do a lot of exercise during recess.",
			fullAnswer: ["2413"],
			partAnswer: ["2314"],
		},
		Anagram_lunches: {
			title: "Healthier School Lunches",
			numOfText: 5,
			text1: "Another reason is that not all students like the same food, so students need more choices.",
			text2:
				"Thatís why I think healthier food, more choices, and more food would make our school lunches better.",
			text3: "One reason is that students need healthier food to stay healthy.",
			text4: "I believe that students should get better lunches at school.",
			text5: "Finally, some students are still hungry after lunch, so each student should get more food.",
			fullAnswer: ["35214"],
			partAnswer: ["34215"],
			lessAnswer: ["05010"],
		},
		Anagram_uniforms: {
			title: "School uniforms solve many problems",
			numOfText: 6,
			text1: "Another reason is that uniforms make students all equal because no one has more expensive clothes.",
			text2: "In conclusion, wearing uniforms to school is better because it solves many problems.",
			text3: "Finally, uniforms cost less, so families will spend less money.",
			text4: "I think students should wear uniforms to school.",
			text5:
				"One reason is that with uniforms, students will pay less attention to clothes and more attention to learning.",
			text6:
				"For example, a student at a school with uniforms said, ìEveryone works hard. Nobody pays attention to clothes.î",
			fullAnswer: ["465123"],
			partAnswer: ["456123"],
			lessAnswer: ["060100"],
		},
		Anagram_gender_B: {
			title: "Separate classrooms for boys and girls?",
			numOfText: 6,
			text1:
				"In conclusion, having separate classes for boys and girls is a good way to improve studentsí learning.",
			text2:
				"One the one hand, many people say that having separate classes for boys and girls is a good idea because students learn more.",
			text3: "Should boys and girls be in separate classes in school?",
			text4:
				"On the other hand, others argue that separate classes are not a good idea because boys and girls need to learn to work together.",
			text5: "Lastly, recent reports say that boys and girls in separate classes pay more attention to teachers.",
			text6:
				"However, I think that separate classes for boys and girls are better because students feel safer and they also participate more in class discussions.",
			fullAnswer: ["621354"],
			partAnswer: ["521364","421365"],
			lessAnswer: ["601000"],
		},
		Anagram_gender_A: {
			title: "Separate classrooms for boys and girls?",
			numOfText: 6,
			text1: "In conclusion, having separate classes for boys and girls improves their learning.",
			text2: "Lastly, boys and girls participate more in class discussions when they are separated.",
			text3:
				"Another reason is that boys and girls pay less attention to clothes and looks when they are in separate classes.",
			text4: "For instance, a 4th-grade girl said that she speaks up much more in class in her all-girls school.",
			text5: "One reason is that boys and girls in separate classes feel safer and study more.",
			text6: "In my opinion, boys and girls should be in separate classrooms for several reasons.",
			fullAnswer: ["654321", "653421"],
			partAnswer: ["564321", "563421"],
			lessAnswer: ["600001"],
		},
		Anagram_catsordogs: {
			title: "Cats or dogs?",
			numOfText: 3,
			text1: "You can play with your dog and take your dog on walks.",
			text2: "That is why dogs are the best pets.",
			text3: "Some people say that cats are the best pets, but dogs are better pets.",
			fullAnswer: ["231"],
		},
		Anagram_swimming: {
			title: "Swimming",
			numOfText: 3,
			text1: "When you go swimming you can stay close to beach.",
			text2: "That is why I believe that swimming is safe.",
			text3: "Some people say that swimming in the lake is scary, but it is safe.",
			fullAnswer: ["231"],
		},
		Anagram_rain: {
			title: "Rain",
			numOfText: 4,
			text1: "If you do not have rain boots, your feet will get wet when you walk to school.",
			text2: "This is why school should be closed when it rains.",
			text3: "I think that there should be no school when it rains outside.",
			text4: "Also, it is very hard to keep your backpack dry when it is raining.",
			fullAnswer: ["2413"],
		},
		Anagram_salad: {
			title: "Salad",
			numOfText: 4,
			text1: "Salad is healthier than ice cream.",
			text2: "You can put all different types of vegetables in salad.",
			text3: "As a result, salad is filled with lots of vitamins. ",
			text4: "This is why salad is a healthy food.",
			fullAnswer: ["1324"],
		},
		Anagram_naptime: {
			title: "Naptime!",
			numOfText: 4,
			text1:
				"I believe that there should be time to nap during school so students can stay awake during classes.",
			text2: "In conclusion, all schools should give students time to nap during the day.",
			text3: "Another reason is that having good rest will make students remember more during the day.",
			text4: "First, many students have to stay up late working on homework so they do not get enough sleep.",
			fullAnswer: ["1432"],
		},
		Anagram_books: {
			title: "Books!",
			numOfText: 5,
			text1:
				"To start, books allow the person to make a movie in their head by using their imagination as they read.",
			text2: "Also, people can learn new words and learn about many new places by reading books.",
			text3: "In my opinion, books are better than movies.",
			text4: "Are books better than movies?",
			text5:
				"In conclusion, books are better than movies because they give readers a chance to use their imagination to think about new ideas.",
			fullAnswer: ["34215"],
		},
		Anagram_cooking: {
			title: "Cooking!",
			numOfText: 6,
			text1: "I believe it is better to cook meals at home than to eat at restaurants.",
			text2:
				"Others may say that it is better to eat at a restaurant because this allows you to take time to relax after your day.",
			text3:
				"Additionally, when you cook at home you can increase your math skills by measuring the ingredients.",
			text4: "One reason is that cooking food at home gives you chance to choose healthier food options.",
			text5:
				"In conclusion, it is better to prepare your food at home than to go out for a meal because you have greater control over the types of food you eat, more chances to practice math skills and more time to relax!",
			text6: "I do not agree because I think it is actually more relaxing to cook in your home. ",
			fullAnswer: ["143265", "135264"],
			partAnswer: ["100260"],
			lessAnswer: ["100060"],
		},
		Anagram_pets: {
			title: "Pets at school",
			numOfText: 6,
			text1:
				"In conclusion, to create a relaxing class atmosphere and provide chances to learn about animals, pets should be allowed at school. ",
			text2:
				"Furthermore, other types of pets, such as snakes, are really interesting and so students could be provided with opportunities to learn about these animals if these pets were allowed in class.",
			text3: "Students should be allowed to bring their pets to school.",
			text4: "First, dogs and cats can provide students company during their classes.",
			text5: "Some people think dogs and snakes can be scary for some children.",
			text6:
				"I disagree because students can learn how to care for different types of pets so they are not scared anymore.",
			fullAnswer: ["631245", "653412"],
			partAnswer: ["600045", "600012", "630200", "650400"],
			lessAnswer: ["601000"],
		},
		Anagram_bikesorcars: {
			title: "Bicycles or cars!!",
			numOfText: 6,
			text1: "I disagree with that because some bicycles are built to carry multiple people. ",
			text2:
				"Exercise is something that each person should do to keep healthy, but it can be a challenge to find the time to workout.",
			text3:
				"However, some may say that bicycles are not as useful as cars because only one person can fit on a bicycle at a time.",
			text4: "This is why I believe that bicycles are the best choice for transportation.",
			text5:
				"In particular, bicycles allow you to exercise while you travel from place to place, which allows many people to fit in a workout during a busy day.",
			text6: "I think that using a bicycle is better than driving a car.",
			fullAnswer: ["524631", "534621", "423651"],
			lessAnswer: ["000601"],
		},
		Anagram_cellphones: {
			title: "Cell Phones!",
			numOfText: 6,
			text1:
				"Conversely, other people say that cell phones can distract students when they are used in the classroom.",
			text2:
				"I disagree with that because students need to learn how to focus during school even if they have their cell phones.",
			text3:
				"In conclusion, I believe students should be allowed to use cell phones during school to conduct research and learn to be focused.",
			text4:
				"Having a calculator on his or her phone will allow students to be successful in math and science because both classes often require students to solve math problems.",
			text5: "Cell phones have many important applications such as the calculator.",
			text6: "I think that students should be allowed to use cell phones during school.",
			fullAnswer: ["456321", "236541"],
			lessAnswer: ["006001"],
		},
	},

	Connect_pic_therefore_B: {
		text: "Our school football team won the game; ________ our school got a prize.",
		text1: "Our school football team won the game; ",
		text2: " our school got a prize.",
		choice: ["on the other hand", "yet", "however", "therefore"],
		answer: 4,
		picture1: require("../Site/Images/Connect_pic_therefore_B_1.jpg"),
		picture2: require("../Site/Images/Connect_pic_therefore_B_2.jpg"),
		audio: "../Site/audio/Connect_pic_therefore_B.mp3",
	},
	Connect_pic_whereas_B: {
		text: "A ladybug has 6 legs,________ a centipede has 100 legs.",
		text1: "A ladybug has 6 legs, ",
		text2: " a centipede has 100 legs.",
		choice: ["likewise", "whether", "whereas", "moreover"],
		answer: 3,
		picture1: require("../Site/Images/Connect_pic_whereas_B_1.jpg"),
		picture2: require("../Site/Images/Connect_pic_whereas_B_2.jpg"),
		audio: "../Site/audio/Connect_pic_whereas_B.mp3",
	},
	Connect_pic_asaresult: {
		text: "Kim was sick. ________ she stayed home and did not go to school.",
		text1: "Kim was sick.",
		text2: " she stayed home and did not go to school.",
		choice: ["otherwise", "yet", "in contrast", "as a result"],
		answer: 4,
		picture1: require("../Site/Images/Connect_pic_asaresult_1.jpg"),
		picture2: require("../Site/Images/Connect_pic_asaresult_2.jpg"),
		audio: "../Site/audio/Connect_pic_asaresult.mp3",
	},
	Connect_pic_incontrast: {
		text: "Amy’s favorite animal is a dog. _______, Carolina thinks cats are the best pets.",
		text1: "Amy’s favorite animal is a dog. ",
		text2: ", Carolina thinks cats are the best pets.",
		choice: ["in contrast", "for example", "otherwise", "in other word"],
		answer: 1,
		picture1: require("../Site/Images/Connect_pic_incontrast_1.jpg"),
		picture2: require("../Site/Images/Connect_pic_incontrast_2.jpg"),
		audio: "../Site/audio/Connect_pic_incontrast.mp3",
	},
	Connect_pic_inconclusion: {
		text:
			"Jenny scores all of the points for her team. She is the best player on defense. _______, she is the best player on the team.",
		text1: "Jenny scores all of the points for her team. She is the best player on defense. ",
		text2: ", she is the best player on the team.",
		choice: ["on the other hand", "otherwise", "in conclusion", "in contrast"],
		answer: 3,
		picture1: require("../Site/Images/Connect_pic_inconclusion_1.jpg"),
		picture2: require("../Site/Images/Connect_pic_inconclusion_2.jpg"),
		audio: "../Site/audio/Connect_pic_inconclusion.mp3",
	},
	Connect_pic_forinstance: {
		text:
			" Many schools offer team sports for their students. _________students at my school can be part of our soccer team.",
		text1: "Many schools offer team sports for their students. ",
		text2: " students at my school can be part of our soccer team.",
		choice: ["on the other hand", "in conclusion", "for instance", "in spite of that"],
		answer: 3,
		picture1: require("../Site/Images/Connect_pic_forinstance_1.jpg"),
		picture2: require("../Site/Images/Connect_pic_forinstance_2.jpg"),
		audio: "../Site/audio/Connect_pic_forinstance.mp3",
	},
	Connect_pic_nevertheless: {
		text: "Sam broke his leg; ________ he continues to play baseball.",
		text1: "Sam broke his leg; ",
		text2: " he continues to play baseball.",
		choice: ["consequently", "nevertheless", "namely", "thus"],
		answer: 2,
		picture1: require("../Site/Images/Connect_pic_nevertheless_1.jpg"),
		picture2: require("../Site/Images/Connect_pic_nevertheless_2.jpg"),
		audio: "../Site/audio/Connect_pic_nevertheless.mp3",
	},
	Connect_pic_whereas_A: {
		text: "Kobe has an umbrella ________ David does not.",
		text1: "Kobe has an umbrella ",
		text2: " David does not.",
		choice: ["likewise", "whether", "whereas", "moreover"],
		answer: 3,
		picture1: require("../Site/Images/Connect_pic_whereas_A_1.jpg"),
		picture2: require("../Site/Images/Connect_pic_whereas_A_2.jpg"),
		audio: "../Site/audio/Connect_pic_whereas_A.mp3",
	},
	Connect_pic_therefore_A: {
		text: "Nick’s team won the football game; ________ Nick and his father are excited.",
		text1: "Nick’s team won the football game; ",
		text2: " Nick and his father are excited.",
		choice: ["on the other hand", "yet", "however", "therefore"],
		answer: 4,
		picture1: require("../Site/Images/Connect_pic_therefore_A_1.jpg"),
		picture2: require("../Site/Images/Connect_pic_therefore_A_2.jpg"),
		audio: "../Site/audio/Connect_pic_therefore_A.mp3",
	},
	Connect_pic_consequently: {
		text: "Brad studied hard for the test. ________ he got a good grade.",
		text1: "Brad studied hard for the test. ",
		text2: " he got a good grade.",
		choice: ["in contrast", "even though", "consequently", "nonetheless"],
		answer: 3,
		picture1: require("../Site/Images/Connect_pic_consequently_1.jpg"),
		picture2: require("../Site/Images/Connect_pic_consequently_2.jpg"),
		audio: "../Site/audio/Connect_pic_consequently.mp3",
	},
	Connect_pic_inotherwords: {
		text: "Our school will start recycling bottles. _______ all plastic and glass bottles will go in special bins.",
		text1: "Our school will start recycling bottles. ",
		text2: " all plastic and glass bottles will go in special bins.",
		choice: ["nevertheless", "in spite of that", "in other words", "even though"],
		answer: 3,
		picture1: require("../Site/Images/Connect_pic_inotherwords_1.jpg"),
		picture2: require("../Site/Images/Connect_pic_inotherwords_2.jpg"),
		audio: "../Site/audio/Connect_pic_inotherwords.mp3",
	},
	Connect_pic_similarly: {
		text: "Grapes come in many different colors. _________, roses can also have many colors.",
		text1: "Grapes come in many different colors. ",
		text2: ", roses can also have many colors.",
		choice: ["because", "but", "however", "similarly"],
		answer: 4,
		picture1: require("../Site/Images/Connect_pic_similarly_1.jpg"),
		picture2: require("../Site/Images/Connect_pic_similarly_2.jpg"),
		audio: "../Site/audio/Connect_pic_similarly.mp3",
	},
	Connect_pic_onthecontrary: {
		text: "Many people think that whales are fish. _______, they are mammals.",
		text1: "Many people think that whales are fish. ",
		text2: ", they are mammals.",
		choice: ["therefore", "furthermore", "on the contrary", "hense"],
		answer: 3,
		picture1: require("../Site/Images/Connect_pic_onthecontrary_1.jpg"),
		picture2: require("../Site/Images/Connect_pic_onthecontrary_2.jpg"),
		audio: "../Site/audio/Connect_pic_onthecontrary.mp3",
	},
	Connect_pic_asaconsequence: {
		text: "During the class trip, the bus broke down. ________, we were not able to go to the museum.",
		text1: "During the class trip, the bus broke down. ",
		text2: ", we were not able to go to the museum.",
		choice: ["as a consequence", "but", "however", "similarly"],
		answer: 1,
		picture1: require("../Site/Images/Connect_pic_asaconsequence_1.jpg"),
		picture2: require("../Site/Images/Connect_pic_asaconsequence_2.jpg"),
		audio: "../Site/audio/Connect_pic_asaconsequence.mp3",
	},
	Connect_pic_incontrast_B: {
		text: "Mark’s favorite school subject is history. __________, Julie enjoys math class the most.",
		text1: "Mark’s favorite school subject is history. ",
		text2: ", Julie enjoys math class the most.",
		choice: ["at a result", "in contrast", "hence", "therefore"],
		answer: 2,
		picture1: require("../Site/Images/Connect_pic_incontrast_B_A.png"),
		picture2: require("../Site/Images/Connect_pic_incontrast_B_B.png"),
		audio: "../Site/audio/Connect_pic_incontrast_B.mp3",
	},
	Connect_sent_however: {
		text1: "The day was sunny and warm, ",
		text2: "however ",
		choice: ["everybody was at the beach.", "it was summer time.", "there was a strong wind."],
		answer: 2,
		audio: "../Site/audio/Connect_sent_however.mp3",
	},
	Connect_sent_consequently: {
		text1: "During the last battle, most soldiers in the red army were sick. ",
		text2: "Consequently, ",
		choice: [
			"many of the soldiers had bad injuries.",
			"the soldiers were strong enough to  win the battle.",
			"the soldiers were weak and lost the battle. ",
		],
		answer: 3,
		audio: "../Site/audio/Connect_sent_consequently.mp3",
	},
	Connect_sent_otherhand: {
		text1: "Most teachers think that homework is important. ",
		text2: "On the other hand, ",
		choice: [
			"these teachers like to give a lot of homework to students.",
			"many teachers think homework helps students learn.",
			"some teachers think that homework is not important.",
		],
		answer: 3,
		audio: "../Site/audio/Connect_sent_otherhand.mp3",
	},
	Connect_sent_moreover: {
		text1: "We can get books and magazines from our library. ",
		text2: "Moreover, ",
		choice: ["we can not eat in the library.", "we can get videos.", "we can not get video games."],
		answer: 2,
		audio: "../Site/audio/Connect_sent_moreover.mp3",
	},
	Connect_sent_nonetheless: {
		text1: "It rained all day during the school trip to the beach. ",
		text2: "Nonetheless, ",
		choice: ["most of the students had fun.", "the school trip was horrible.", "there even was scary lightning."],
		answer: 1,
		audio: "../Site/audio/Connect_sent_nonetheless.mp3",
	},
	Connect_sent_incontrast: {
		text1: "Cats like to eat fish. ",
		text2: "In contrast, ",
		choice: ["cats like to eat tuna fish.", "dogs like to chew bones.", "cats eat food made of fish."],
		answer: 2,
		audio: "../Site/audio/Connect_sent_incontrast.mp3",
	},
	Connect_sent_nonetheless_B: {
		text1: "A rain storm started during school recess. ",
		text2: "Nonetheless, ",
		choice: [
			"The students continued to play outside.",
			"The students decided to go inside.",
			"The students went to the library to read.",
		],
		answer: 1,
		audio: "../Site/audio/Connect_sent_nonetheless_B.mp3",
	},
	Connect_sent_however_B: {
		text1: "Some students enjoy reading. ",
		text2: "However, ",
		choice: [
			"some adults also enjoy reading.",
			"some students prefer to watch movies.",
			"some students read comic books.",
		],
		answer: 2,
		audio: "../Site/audio/Connect_sent_however_B.mp3",
	},
	Connect_sent_accordingly: {
		text1: "Annie wants to become a better piano player. ",
		text2: "Accordingly, ",
		choice: [
			"She practices the piano each day.",
			"She would also like to play the violin.",
			"She does not play piano very often.",
		],
		answer: 1,
		audio: "../Site/audio/Connect_sent_accordingly.mp3",
	},
	Anaphora_material: {
		text1: "Major volcanic eruptions release huge quantities of gases and ash into the air.",
		keyword: "These materials",
		text2: "can stay in the upper atmosphere for months or years.",
		choice: ["volcanic eruptions", "huge quantities", "gases and ash"],
		answer: 3,
		audio: "../Site/audio/Anaphora_material.mp3",
	},
	Anaphora_explorer: {
		text1:
			" Scott’s team and Johnson’s team tried to reach the top of the tallest mountain. Johnson’s team made it to the top first because of",
		keyword: "this explorer’s",
		text2: "leadership.",
		choice: ["Scott", "team", "Johnson"],
		answer: 3,
		audio: "../Site/audio/Anaphora_explorer.mp3",
	},
	Anaphora_movement: {
		text1:
			"China resisted the move for change. In 1989 students protested to demand changes, but the army opposed these changes. Troops were sent to stop",
		keyword: "the movement",
		text2: ".",
		choice: [
			"China resisted the move for change",
			"students protested to demand changes",
			"the army opposed the changes",
		],
		answer: 2,
		audio: "../Site/audio/Anaphora_movement.mp3",
	},
	Anaphora_phenom: {
		text1:
			"Our planet is made up of many layers of rock. The top layers are formed by solid rock. The deep layer is so hot that some rock melts. Volcanoes are formed when the melted rock pushes its way up through the top layers.",
		keyword: "This phenomenon",
		text2: "has been broadly studied.",
		choice: [
			"the top layers of solid rock",
			"the melted rock pushes its way up",
			"deep layer is so hot that rock melts",
		],
		answer: 3,
		audio: "../Site/audio/Anaphora_phenom.mp3",
	},
	Anaphora_system: {
		text1:
			"In April 2010, an international company caused a big oil explosion in the Gulf of Mexico. Scientists worry about the impact of the oil spill on the sea life. The sea waters are home to many animals that can suffer from the spill. Scientists say",
		keyword: "this system",
		text2: "was already weak and needs to be protected.",
		choice: [
			"an international company caused a big oil explosion ",
			"scientists worry about the impact of the oil spill",
			"sea waters are home to many animals ",
		],
		answer: 3,
		audio: "../Site/audio/Anaphora_system.mp3",
	},
	Anaphora_aunt: {
		text1: "",
		keyword: "It",
		text2:
			"must have been difficult on your aunt, having to work so many hours during the holiday season at the department store.",
		choice: ["the holiday season", "having to work many hours", "the department store"],
		answer: 2,
		audio: "../Site/audio/Anaphora_aunt.mp3",
	},
	Anaphora_fest: {
		text1: "",
		keyword: "It",
		text2:
			"has often been compared to Summer Fest, one of the largest festivals in the south. Stuartville’s streets have been as crowded over the last few days as they are during Summer Fest. Since it began last week, three million people have attended the Stuartville Fisherman’s Festival.",
		choice: ["Summer Fest", "three million people", "Stuartville Fisherman’s Festival"],
		answer: 3,
		audio: "../Site/audio/Anaphora_fest.mp3",
	},
	Anaphora_liquid: {
		text1: "Air temperature is measured using thermometers. Thermometers work because liquids expand when",
		keyword: "they",
		text2: "are heated and contract when they are cooled.",
		choice: ["liquids", "thermometers", "air"],
		answer: 1,
		audio: "../Site/audio/Anaphora_liquid.mp3",
	},
	Anaphora_voting: {
		text1:
			"We are citizens of a free country and we have the right to vote. Whether or not the system works perfectly,",
		keyword: "it",
		text2: "is better than a system with no voting.",
		choice: ["a free system", "a system of citizens", "a voting system"],
		answer: 2,
		audio: "../Site/audio/Anaphora_voting.mp3",
	},
	Anaphora_earth: {
		text1: "The Earth rotates on its axis once every 24 hours.",
		keyword: "It",
		text2: "orbits the sun once every 365 days.",
		choice: ["The Earth", "The Earth’s axis", "The Sun"],
		answer: 1,
		audio: "../Site/audio/Anaphora_earth.mp3",
	},
	Anaphora_olympicgames: {
		text1:
			"During the Olympic Games, countries from around the world send athletes to compete in various sporting events.",
		keyword: "These competitions",
		text2: "are divided into two categories: winter and summer.",
		choice: ["Countries from around the world", "athletes", "sporting events"],
		answer: 3,
		audio: "../Site/audio/Anaphora_olympicgames.mp3",
	},
	Anaphora_covered: {
		text1:
			"Mars’ red color comes from a chemical in its soil. When this chemical touches oxygen, it rusts and becomes red in color. How exactly the entire planet came to be covered in this red soil is a subject of debate among scientists. Some believe that",
		keyword: "this process",
		text2: "occurred long ago when water still flowed on Mars’ surface, spreading the dust across the planet.",
		choice: ["Mars’ red color", "Chemical touches oxygen", "the planet came to be covered in red soil"],
		answer: 3,
		audio: "../Site/audio/Anaphora_chemical.mp3",
	},
	Anaphora_difficultplane: {
		text1:
			"In 1903, the Wright brothers flew their first airplane. To fly the plane, the pilot laid on his stomach. Their plane was difficult to control in the air and was damaged after only four flights. The Wright brothers tried to solve",
		keyword: "this problem",
		text2: "in the next plane that they built.",
		choice: [
			"the Wright brothers flew their first airplane",
			"the pilot laid on his stomach",
			"the plane was difficult to control and was damaged",
		],
		answer: 3,
		audio: "../Site/audio/Anaphora_difficultplane.mp3",
	},
	Anaphora_scienceprojects: {
		text1:
			"For weeks, the class prepared their science projects. Finally, the day of the Science Fair arrived and students were excited to showcase their",
		keyword: "hard work",
		text2: ".",
		choice: ["week", "the class", "the science projects"],
		answer: 3,
		audio: "../Site/audio/Anaphora_scienceprojects.mp3",
	},
	Anaphora_animals: {
		text1:
			"During the school trip to the zoo, many of the students noticed that the animals were all sleeping out of sight. They didn’t seem like",
		keyword: "they",
		text2: "wanted to be bothered with the visitors.",
		choice: ["the animals", "the trip", "the zoo"],
		answer: 1,
		audio: "../Site/audio/Anaphora_animals.mp3",
	},
	Anaphora_telescope: {
		text1:
			"The scientist worked to get the telescope ready for the meteor shower. Working tirelessly for months the day final came for the",
		keyword: "project",
		text2: "to be realized.",
		choice: ["the telescope", "the meteor shower", "working tirelessly"],
		answer: 1,
		audio: "../Site/audio/Anaphora_telescope.mp3",
	},
	Anaphora_stateexam: {
		text1: "For the students,",
		keyword: "the time",
		text2: "had come. After months of studying they were finally ready to take their state exam.",
		choice: ["the state exam", "studying", "the students"],
		answer: 1,
		audio: "../Site/audio/Anaphora_stateexam.mp3",
	},
	Anaphora_financialfallout: {
		text1:
			"When the financial fallout of the Great Depression began in the mid 1920’s the country could not predict its eventual impact. It was a time of",
		keyword: "great turmoil",
		text2: "for the United States that would soon define the nation’s trajectory.",
		choice: ["the financial fallout", "the Great Depression", "c)	the impact"],
		answer: 3,
		audio: "../Site/audio/Anaphora_financialfallout.mp3",
	},
	// Section 4
	Morpho_activity: {
		text1: "The children are very",
		text2: "",
		keyword: "activity",
		answer: ["active", "activ"],
		audio: "../Site/audio/Morpho_activity.mp3",
	},
	Morpho_ethnicity: {
		text1: "The city has many",
		text2: "groups",
		keyword: "ethnicity",
		answer: ["ethnic"],
		audio: "../Site/audio/Morpho_ethnicity.mp3",
	},
	Morpho_civility: {
		text1: "The children should be",
		text2: "",
		keyword: "civility",
		answer: ["civilized", "civilysed", "civilised", "civil"],
		audio: "../Site/audio/Morpho_civility.mp3",
	},
	Morpho_categorical: {
		text1: "These words go in the same",
		text2: "",
		keyword: "categorical",
		answer: ["categorie", "catagory", "catigory", "categore", "catagorie", "category"],
		audio: "../Site/audio/Morpho_categorical.mp3",
	},
	Morpho_complexity: {
		text1: "The problem is",
		text2: "",
		keyword: "complexity",
		answer: ["complex"],
		audio: "../Site/audio/Morpho_complexity.mp3",
	},
	Morpho_beneficial: {
		text1: "Good health is a",
		text2: "",
		keyword: "beneficial",
		answer: ["benifit", "benefit"],
		audio: "../Site/audio/Morpho_beneficial.mp3",
	},
	Morpho_durability: {
		text1: "This suitcase is",
		text2: "",
		keyword: "durability",
		answer: ["duruble", "durabul", "durible", "durable"],
		audio: "../Site/audio/Morpho_durability.mp3",
	},
	Morpho_contribution: {
		text1: "How will you",
		text2: "",
		keyword: "contribution",
		answer: ["contribute"],
		audio: "../Site/audio/Morpho_contribution.mp3",
	},
	Morpho_optional: {
		text1: "What is the other",
		text2: "",
		keyword: "optional",
		answer: ["option"],
		audio: "../Site/audio/Morpho_optional.mp3",
	},
	Morpho_cultural: {
		text1: "He studies their",
		text2: "",
		keyword: "cultural",
		answer: ["cultures", "culture"],
		audio: "../Site/audio/Morpho_cultural.mp3",
	},
	Morpho_invasion: {
		text1: "The aliens were ready to",
		text2: "",
		keyword: "invasion",
		answer: ["invaid", "invade", "invaed", "invade"],
		audio: "../Site/audio/Morpho_invasion.mp3",
	},
	Morpho_topical: {
		text1: "She is thinking about a new",
		text2: "",
		keyword: "topical",
		answer: ["topic"],
		audio: "../Site/audio/Morpho_topical.mp3",
	},
	Morpho_availability: {
		text1: "The video will soon be",
		text2: "",
		keyword: "availability",
		answer: ["availuble", "availible", "availeble", "availoble", "available"],
		audio: "../Site/audio/Morpho_availability.mp3",
	},
	Morpho_expansion: {
		text1: "The business will",
		text2: "",
		keyword: "expansion",
		answer: ["expand"],
		audio: "../Site/audio/Morpho_expansion.mp3",
	},
	Morpho_discrimination: {
		text1: "He works hard not to",
		text2: "",
		keyword: "discrimination",
		answer: [
			"discriminate",
			"discrimonate",
			"discrimunate",
			"discrimanate",
			"discriminait",
			"discrimonait",
			"discrimunait",
			"discrimanait",
		],
		audio: "../Site/audio/Morpho_discrimination.mp3",
	},
	Morpho_division: {
		text1: "The cake is hard to",
		text2: "",
		keyword: "division",
		answer: ["divide", "divied"],
		audio: "../Site/audio/Morpho_division.mp3",
	},
	Morpho_possession: {
		text1: "How many toys do you",
		text2: "",
		keyword: "possession",
		answer: ["posess", "pozess", "poses", "pozes"],
		audio: "../Site/audio/Morpho_possession.mp3",
	},
	Morpho_typical: {
		text1: "What is your favorite",
		text2: "of food?",
		keyword: "typical",
		answer: ["type", "tipe"],
		audio: "../Site/audio/Morpho_typical.mp3",
	},
	Morpho_astronomical: {
		text1: "He loves to learn about",
		text2: "",
		keyword: "astronomical",
		answer: [
			"astronomy",
			"astronemy",
			"astronimy",
			"astronamy",
			"astronumy",
			"astronemee",
			"astronimee",
			"astronamee",
			"astronumee",
		],
		audio: "../Site/audio/Morpho_astronomical.mp3",
	},
	Morpho_responsive: {
		text1: "She raised her hand to give her",
		text2: "",
		keyword: "responsive",
		answer: ["response", "respons", "responce"],
		audio: "../Site/audio/Morpho_responsive.mp3",
	},
	Morpho_scandalous: {
		text1: "The missing car keys caused a large",
		text2: "",
		keyword: "scandalous",
		answer: ["scandal", "scandel", "scandil", "scandol", "scandul"],
		audio: "../Site/audio/Morpho_scandalous.mp3",
	},
	Morpho_abundant: {
		text1: "There was an",
		text2: "of cookies at the bakery.",
		keyword: "abundant",
		answer: ["abundant", "abundent", "abundint", "abundunt"],
		audio: "../Site/audio/Morpho_abundant.mp3",
	},
	// Section 5
	SYNTAX_PICTURES: {
		Syntax_pic_1: {
			picture1: require("../Site/Images/Comprehending_S_Syntax_pic_1a.JPG"),
			picture2: require("../Site/Images/Comprehending_S_Syntax_pic_1b.JPG"),
			picture3: require("../Site/Images/Comprehending_S_Syntax_pic_1c.JPG"),
			picture4: require("../Site/Images/Comprehending_S_Syntax_pic_1d.JPG"),
			audio: "../Site/audio/Syntax_pic_1.mp3",
			answer: 1,
		},
		Syntax_pic_2: {
			picture1: require("../Site/Images/Comprehending_S_Syntax_pic_2a.JPG"),
			picture2: require("../Site/Images/Comprehending_S_Syntax_pic_2b.JPG"),
			picture3: require("../Site/Images/Comprehending_S_Syntax_pic_2c.JPG"),
			picture4: require("../Site/Images/Comprehending_S_Syntax_pic_2d.JPG"),
			audio: "../Site/audio/Syntax_pic_2.mp3",
			answer: 1,
		},
		Syntax_pic_3: {
			picture1: require("../Site/Images/Comprehending_S_Syntax_pic_3a.JPG"),
			picture2: require("../Site/Images/Comprehending_S_Syntax_pic_3b.JPG"),
			picture3: require("../Site/Images/Comprehending_S_Syntax_pic_3c.JPG"),
			picture4: require("../Site/Images/Comprehending_S_Syntax_pic_3d.JPG"),
			audio: "../Site/audio/Syntax_pic_3.mp3",
			answer: 3,
		},
		Syntax_pic_4: {
			picture1: require("../Site/Images/Comprehending_S_Syntax_pic_4a.JPG"),
			picture2: require("../Site/Images/Comprehending_S_Syntax_pic_4b.JPG"),
			picture3: require("../Site/Images/Comprehending_S_Syntax_pic_4c.JPG"),
			picture4: require("../Site/Images/Comprehending_S_Syntax_pic_4d.JPG"),
			audio: "../Site/audio/Syntax_pic_4.mp3",
			answer: 3,
		},
		Syntax_pic_5: {
			picture1: require("../Site/Images/Comprehending_S_Syntax_pic_5a.JPG"),
			picture2: require("../Site/Images/Comprehending_S_Syntax_pic_5b.JPG"),
			picture3: require("../Site/Images/Comprehending_S_Syntax_pic_5c.JPG"),
			picture4: require("../Site/Images/Comprehending_S_Syntax_pic_5d.JPG"),
			audio: "../Site/audio/Syntax_pic_5.mp3",
			answer: 2,
		},
		Syntax_pic_6: {
			picture1: require("../Site/Images/Comprehending_S_Syntax_pic_6a.JPG"),
			picture2: require("../Site/Images/Comprehending_S_Syntax_pic_6b.JPG"),
			picture3: require("../Site/Images/Comprehending_S_Syntax_pic_6c.JPG"),
			picture4: require("../Site/Images/Comprehending_S_Syntax_pic_6d.JPG"),
			audio: "../Site/audio/Syntax_pic_6.mp3",
			answer: 2,
		},
		Syntax_pic_7: {
			picture1: require("../Site/Images/Comprehending_S_Syntax_pic_7a.JPG"),
			picture2: require("../Site/Images/Comprehending_S_Syntax_pic_7b.JPG"),
			picture3: require("../Site/Images/Comprehending_S_Syntax_pic_7c.JPG"),
			picture4: require("../Site/Images/Comprehending_S_Syntax_pic_7d.JPG"),
			audio: "../Site/audio/Syntax_pic_7.mp3",
			answer: 3,
		},
		Syntax_pic_8: {
			picture1: require("../Site/Images/Comprehending_S_Syntax_pic_8a.JPG"),
			picture2: require("../Site/Images/Comprehending_S_Syntax_pic_8b.JPG"),
			picture3: require("../Site/Images/Comprehending_S_Syntax_pic_8c.JPG"),
			picture4: require("../Site/Images/Comprehending_S_Syntax_pic_8d.JPG"),
			audio: "../Site/audio/Syntax_pic_8.mp3",
			answer: 1,
		},
		Syntax_pic_9: {
			picture1: require("../Site/Images/Comprehending_S_Syntax_pic_9a.JPG"),
			picture2: require("../Site/Images/Comprehending_S_Syntax_pic_9b.JPG"),
			picture3: require("../Site/Images/Comprehending_S_Syntax_pic_9c.JPG"),
			picture4: require("../Site/Images/Comprehending_S_Syntax_pic_9d.JPG"),
			audio: "../Site/audio/Syntax_pic_9.mp3",
			answer: 1,
		},
		Syntax_pic_10: {
			picture1: require("../Site/Images/Comprehending_S_Syntax_pic_10a.JPG"),
			picture2: require("../Site/Images/Comprehending_S_Syntax_pic_10b.JPG"),
			picture3: require("../Site/Images/Comprehending_S_Syntax_pic_10c.JPG"),
			picture4: require("../Site/Images/Comprehending_S_Syntax_pic_10d.JPG"),
			audio: "../Site/audio/Syntax_pic_10.mp3",
			answer: 1,
		},
		Syntax_pic_11: {
			picture1: require("../Site/Images/Comprehending_S_Syntax_pic_11a.JPG"),
			picture2: require("../Site/Images/Comprehending_S_Syntax_pic_11b.JPG"),
			picture3: require("../Site/Images/Comprehending_S_Syntax_pic_11c.JPG"),
			picture4: require("../Site/Images/Comprehending_S_Syntax_pic_11d.JPG"),
			audio: "../Site/audio/Syntax_pic_11.mp3",
			answer: 1,
		},
	},
	// Section 6
	DEFINITIONS_AWARENESS: {
		def_aware_umbrella: {
			text1:
				"An umbrella is what you use so you do not get wet in the rain; it has fabric over a frame that you can fold.",
			text2:
				"An umbrella is something that stops the rain and it has some fabric over a type of frame that folds.",
			text3:
				"An umbrella is an object that provides protection from the rain, made of fabric stretched over a folding frame.",
			keyword: "Umbrella",
			answer: [1, 1, 2, 3],
			audio: "../Site/audio/def_aware_umbrella.mp3",
		},
		def_aware_clown: {
			text1: "A clown is someone with funny clothes that makes lots of jokes to make adults and children laugh.",
			text2: "A clown is when you dress funny and you make lots of jokes for people to laugh.",
			text3: "A clown is an actor who wears odd clothes and entertains people using jokes and tricks.",
			keyword: "Clown",
			answer: [1, 1, 2, 3],
			audio: "../Site/audio/def_aware_clown.mp3",
		},
		def_aware_debate: {
			text1: "A debate is a discussion of two or more opposing viewpoints.",
			text2: "A debate is when you argue about something with others.",
			text3: "A debate is a thing where people talk and discuss their opinions.",
			keyword: "Debate",
			answer: [2, 1, 1, 1],
			audio: "../Site/audio/def_aware_debate.mp3",
		},
		def_aware_holiday: {
			text1:
				"A holiday is some time when most adults stop working and they remember or celebrate a person or something else.",
			text2:
				"A holiday is a day on which usual work is suspended in honor or celebration of some person or event.",
			text3:
				"A holiday is when you do not have to go to work because you are remembering or celebrating someone or something.",
			keyword: "Holiday",
			answer: [1, 2, 1, 2],
			audio: "../Site/audio/def_aware_holiday.mp3",
		},
		def_aware_concert: {
			text1: "A concert is a musical performance given in public.",
			text2: "A concert is where you go to listen to music with other people.",
			text3: "A concert is somewhere people go to hear music with others.",
			keyword: "Concert",
			answer: [2, 1, 2, 1],
			audio: "../Site/audio/def_aware_concert.mp3",
		},
		def_aware_confusion: {
			text1: "Confusion is what you feel when you do not know what is going on.",
			text2: "Confusion is the state of being uncertain or unclear about something.",
			text3: "Confusion is when people don’t know what to do.",
			keyword: "Confusion",
			answer: [1, 2, 1, 2],
			audio: "../Site/audio/def_aware_confusion.mp3",
		},
	},
	// Section 7
	EPISTEMIC_MARKERS: {
		rock_from_space: {
			title1: "The Rock is from Space: Sure or Unsure?",
			title2: "Is the rock from space? How sure is each scientist?",
			text1:
				"The scientists ran tests to see if a rock came from space. Based on the results of their tests, some scientists are very sure the rock is from the space and other scientists have doubts. After reading what each scientist said, you decide how sure each scientist is!",
		},
		epis_impossible: {
			text1: "It is impossible that the rock is from space.",
			answer: 4,
			audio: "../Site/audio/epis_impossible.mp3",
		},
		epis_certainly: {
			text1: "Certainly, the rock is from space.",
			answer: 1,
			audio: "../Site/audio/epis_certainly.mp3",
		},
		epis_unlikely: {
			text1: "It is unlikely that the rock is from space.",
			answer: 3,
			audio: "../Site/audio/epis_unlikely.mp3",
		},
		epis_unquestion: {
			text1: "It is unquestionable that the rock is from space.",
			answer: 1,
			audio: "../Site/audio/epis_unquestion.mp3",
		},
		epis_suggest: {
			text1: "Results suggest that the rock is from space.",
			answer: 2,
			audio: "../Site/audio/epis_suggest.mp3",
		},
		epis_possible: {
			text1: "It is possible that the rock is from space.",
			answer: 4,
			audio: "../Site/audio/epis_possible.mp3",
		},
		epis_obvious: {
			text1: "It is obvious that the rock is from space.",
			answer: 1,
			audio: "../Site/audio/epis_obvious.mp3",
		},
		epis_possiblebutunlikely: {
			text1: "It is possible but unlikely that the rock is from space.",
			answer: 3,
			audio: "../Site/audio/epis_possiblebutunlikely.mp3",
		},
		epis_probably: {
			text1: "The rock is probably from space.",
			answer: 2,
			audio: "../Site/audio/epis_probably.mp3",
		},
		epis_presumably: {
			text1: "Presumably, the rock is from space.",
			answer: 2,
			audio: "../Site/audio/epis_presumably.mp3",
		},
		epis_conclusively: {
			text1: "Conclusively, the rock is from space.",
			answer: 1,
			audio: "../Site/audio/epis_conclusively.mp3",
		},
		epis_acc_appears: {
			text1: "It appears that the rock is from space.",
			answer: 2,
			audio: "../Site/audio/epis_acc_appears.mp3",
		},
		epis_acc_presumably: {
			text1: "Presumably, the rock is from space. ",
			answer: 2,
			audio: "../Site/audio/epis_acc_presumably.mp3",
		},
		epis_acc_certainlynot: {
			text1: "The rock is certainly not from space.           ",
			answer: 4,
			audio: "../Site/audio/epis_acc_certainlynot.mp3",
		},
		epis_acc_conclusively: {
			text1: "Conclusively, the rock is from space.",
			answer: 1,
			audio: "../Site/audio/epis_acc_conclusively.mp3",
		},
		epis_acc_suggest: {
			text1: "Results suggest that the rock is from space.",
			answer: 2,
			audio: "../Site/audio/epis_acc_suggest.mp3",
		},
		epis_acc_unquestion: {
			text1: "It is unquestionable that the rock is from space.",
			answer: 1,
			audio: "../Site/audio/epis_acc_unquestion.mp3",
		},
		epis_acc_unlikelybut: {
			text1: "It is unlikely but possible that the rock is from space.",
			answer: 3,
			audio: "../Site/audio/epis_acc_unlikelybut.mp3",
		},
		is_Jessie_coming: {
			title1: "Is Jessie Coming to school today?: Sure or Unsure?",
			title2: "Is Jessie Coming to school today? How sure are Jessie's friends?",
			text1:
				"A group of friends is trying to figure out if Jessie is coming to visit their class today. Some friends are very sure Jessie will come and some friends have doubts. After reading what each friend said, you decide how sure each friend is!",
		},
		epis_soc_probably: {
			text1: "Jessie is probably coming today.",
			answer: 2,
			audio: "../Site/audio/epis_soc_probably.mp3",
		},
		epis_soc_impossible: {
			text1: "It is impossible that Jessie is coming today.",
			answer: 4,
			audio: "../Site/audio/epis_soc_impossible.mp3",
		},
		epis_soc_certainly: {
			text1: "Certainly, Jessie is coming today.",
			answer: 1,
			audio: "../Site/audio/epis_soc_certainly.mp3",
		},
		epis_soc_unlikely: {
			text1: "Jessie is unlikely to come today.",
			answer: 3,
			audio: "../Site/audio/epis_soc_unlikely.mp3",
		},
		epis_soc_seems: {
			text1: "It seems that Jessie is coming today.",
			answer: 2,
			audio: "../Site/audio/epis_soc_seems.mp3",
		},
		epis_soc_apparently: {
			text1: "Apparently, Jessie is coming today.",
			answer: 2,
			audio: "../Site/audio/epis_soc_apparently.mp3",
		},
		epis_soc_possible: {
			text1: "It is possible but unlikely that Jessie is coming today. ",
			answer: 3,
			audio: "../Site/audio/epis_soc_possible.mp3",
		},
	},
	// Section 8
	METALINGUISTIC: {
		meta_supportclaim: {
			newspaper: "Newspaper:",
			news: "Students need recess to have fun and relax at school.",
			people: "Paul said: ",
			idea: "I agree. In addition, recess is an important time to make friends.",
			ask: "Paul is giving Ö",
			img: "meta_supportclaim.png",
			options: ["a counterclaim", "some evidence", "a conclusion", "another supporting claim"],
			answer: 4,
		},
		meta_contradictingA: {
			newspaper: "Newspaper:",
			news: "Students need recess to have fun and relax at school.",
			people: "Jamie said:",
			idea: "I donít think so. Students do not need recess because they can have fun after school.",
			ask: "In the sentence above, Jamie isÖ",
			img: "meta_contradictingA.png",
			options: [
				"emphasizing the newspaperís idea",
				"supporting the newspaperís idea",
				"contradicting with the newspaperís idea ",
				"misrepresenting with the newspaperís idea",
			],
			answer: 3,
		},
		meta_paraphrase: {
			newspaper: "Newspaper:",
			news: "Recess is the perfect time for students to build friendships.",
			people: "Tina's essay:",
			idea: "The newspaper article says that students can make friends during recess.",
			ask: "In her essay, Tina presentsÖ",
			img: "meta_paraphrase.png",
			options: ["an overstatement", "a paraphrase ", "a contradiction", "a misinterpretation"],
			answer: 2,
		},
		meta_disagreeing: {
			newspaper: "Newspaper:",
			news: "Students need recess to have fun and relax at school.",
			people: "Jamie said",
			idea: "I donít think so. Students do not need recess because they can have fun after school.",
			ask: "In the sentence above, Jamie isÖ",
			img: "meta_disagreeing.png",
			options: [
				"introducing the newspaperís idea",
				"clarifying the newspaperís idea",
				"agreeing with the newspaperís idea",
				"disagreeing with the newspaperís idea",
			],
			answer: 4,
		},
		meta_quoting: {
			newspaper: "Newspaper:",
			news: "Recess is the perfect time for students to make friends.",
			people: "Cindyís essay",
			idea: "Students should have recess because it ìis the perfect time for students to make friends.î",
			ask: "In her essay, Cindy isÖ",
			img: "meta_quoting.png",
			options: [
				"opposing the newspaperís idea",
				"quoting the newspaperís idea",
				"describing the newspaperís idea",
				"exaggerating the newspaperís idea ",
			],
			answer: 2,
		},
		meta_counterclaim: {
			newspaper: "Newspaper:",
			news: "Recess is the perfect time for students to make friends.",
			people: "Joseís essay",
			idea: "But other people say that recess wastes school time.",
			ask: "In his essay, Jose presents Ö",
			img: "meta_counterclaim.png",
			options: ["a counterclaim ", "a recommendation ", "a paraphrase", "a supporting claim"],
			answer: 1,
		},
		meta_precise: {
			newspaper: "Newspaper:",
			news: "Recess is the perfect time for students to build friendships.",
			people: "Lauraís essay",
			idea: "In the U.S., 92% of elementary school teachers reported that recess helps students make friends.",
			ask: "In her essay, Laura presents Ö",
			img: "meta_precise.png",
			options: [
				"a vague statement",
				"a contradictory statement",
				"a redundant statement",
				"a precise  statement",
			],
			answer: 4,
		},
		meta_generalize: {
			newspaper: "Newspaper:",
			news: "Recess is the perfect time for students to build friendships.",
			people: "Emmaís essay",
			idea: "In fact, I like recess, so all kids like recess. ",
			ask: "In her essay, Emma presents Ö",
			img: "meta_generalize.png",
			options: ["an understatement", "a generalization", "a hypothesis", "a contradiction "],
			answer: 2,
		},
		meta_citing: {
			newspaper: "Newspaper:",
			news: "Recess is the perfect time for students to build friendships.",
			people: "Mariaís essay",
			idea: "Students should have recess because it ìis the perfect time for students to build friendships.î",
			ask: "In her essay, Maria isÖ",
			img: "meta_citing.png",
			options: [
				"contradicting the newspaperís idea",
				"citing the newspaperís idea",
				"overstating the newspaperís idea",
				"misinterpreting the newspaperís idea",
			],
			answer: 2,
		},
		meta_contradictory: {
			newspaper: "Newspaper:",
			news: "Recess is the perfect time for students to build friendships.",
			people: "Chenísessay",
			idea:
				"Recess is always great for making friends. During recess all kids fight with other kids and get in trouble.",
			ask: "In his essay, Chen presents Ö",
			img: "meta_contradictory.png",
			options: [
				"logical statements",
				"contradictory statements",
				"redundant statements",
				"persuasive statements",
			],
			answer: 2,
		},
		meta_exaggeration: {
			newspaper: "Newspaper:",
			news: "Music makes students happy.",
			people: "Jenny said",
			idea: "Yes, music makes all students happier than anything else in the world.",
			ask: "In the sentence above, Jenny is givingÖ",
			img: "meta_exaggeration.png",
			options: ["a disagreement ", "an exaggeration  ", "a clarification", "an explanation "],
			answer: 2,
		},
		meta_example: {
			newspaper: "Newspaper:",
			news: "Music makes students happy.",
			people: "Changís essay",
			idea: "Students were happy when the teacher played music.",
			ask: "In his essay, Chang presentsÖ",
			img: "meta_example.png",
			options: ["an example", "a rebuttal ", "a contrast", "a summary "],
			answer: 1,
		},
		meta_generalization: {
			newspaper: "Newspaper:",
			news: "Music makes students happy.",
			people: "Pabloís essay",
			idea: "Donna and John like music, so all students like music",
			ask: "In his essay, Pablo presentsÖ",
			img: "meta_generalization.png",
			options: ["an evaluation ", "a generalization  ", "a recommendation", "a contradiction "],
			answer: 2,
		},
		meta_contradictingB: {
			newspaper: "Newspaper:",
			news: "Music makes students happy.",
			people: "Alexaís essay",
			idea: "I disagree. Most students donít like music because itís too loud.",
			ask: "In her essay, Alexa isÖ",
			img: "meta_contradictingB.png",
			options: [
				"emphasizing the newspaperís idea ",
				"contradicting the newspaperís idea ",
				"understating the newspaperís idea ",
				"underscoring the newspaperís idea ",
			],
			answer: 2,
		},
		meta_countering: {
			newspaper: "Newspaper:",
			news: "Music makes students happy.",
			people: "Marlonís essay",
			idea: "Some music makes me feel sad.",
			ask: "In his essay, Marlon isÖ",
			img: "meta_countering.png",
			options: [
				"paraphrasing the newspaperís idea ",
				"backing the newspaperís idea ",
				"citing the newspaperís idea ",
				"countering the newspaperís idea ",
			],
			answer: 4,
		},
		meta_position: {
			newspaper: "Newspaper:",
			news: "Music makes students happy",
			people: "Shondraís essay",
			idea: "In my opinion, music does not make all students happy.",
			ask: "In her essay, Shondra presentsÖ",
			img: "meta_position.png",
			options: ["a source ", "an explanation ", "a definition ", "a position "],
			answer: 4,
		},
		meta_confirming: {
			newspaper: "Newspaper:",
			news: "Music makes students happy.",
			people: "Jimís essay",
			idea: "Yes, I agree. Everybody in our school is happy during music time.",
			ask: "In his essay, Jim isÖ",
			img: "meta_confirming.png",
			options: [
				"confirming the newspaperís idea ",
				"introducing the newspaperís idea ",
				"rebutting the newspaperís idea ",
				"misrepresenting the newspaperís idea ",
			],
			answer: 1,
		},
		meta_inconsistent: {
			newspaper: "Newspaper:",
			news: "Music makes students happy.",
			people: "Mariaís essay",
			idea: "Music makes students sad. Most students are happy when they listen to music.",
			ask: "In her essay, Maria presentsÖ",
			img: "meta_inconsistent.png",
			options: [
				"coherent information ",
				"credible information ",
				"hypothetical information ",
				"inconsistent information  ",
			],
			answer: 4,
		},
		meta_fallacy: {
			newspaper: "Newspaper:",
			news: "Music makes students happy.",
			people: "Kejiaís essay",
			idea: "Music does not make me happy, so it does not make anyone happy.",
			ask: "In the sentence above, Kejia is givingÖ",
			img: "meta_fallacy.png",
			options: ["a fallacy ", "an understatement ", "a paraphrase ", "a citation "],
			answer: 1,
		},
	},
};

export default (state = defaultState, action) => {
	if (action.type === "add_sessionNum") {
		const newState = JSON.parse(JSON.stringify(state));
		newState.sessionNum = newState.sessionNum + 1;
		return newState;
	}
	if (action.type === "update_fontSize") {
		const newState = JSON.parse(JSON.stringify(state));
		newState.fontSize = action.value;
		// console.log(action.value)
		return newState;
	}
	if (action.type === "ANSWER_QUESTION") {
		const newState = JSON.parse(JSON.stringify(state));
		if (newState.questionAns === "") {
			newState.questionAns = action.questionAns;
			newState.questionAnsSum = action.questionAns;
			newState.questions = action.question;
			newState.questionSum = action.question;
		} else {
			newState.questionAns += "," + action.questionAns;
			newState.questionAnsSum += "+" + action.questionAns;
			newState.questions += "," + action.question;
			newState.questionSum += "+" + action.question;
		}
		newState.numQuestions += 1;
		return newState;
	}
	if (action.type === "CLEAR_NUM_QUESTION") {
		const newState = JSON.parse(JSON.stringify(state));
		newState.numQuestions = 0;
		return newState;
	}

	return state;
};
